import { createContext, useContext } from 'react';
import { useLocalStorage } from '@/hooks/use-local-storage'; // We'll need to create this hook too or just inline it if it's small, but let's check if it exists or I should create it. App.tsx had it inline. I will extract it.


export type Language = 'en' | 'hi';

interface Contact {
    id: string;
    name: string;
    phone: string;
}

interface SettingsContextType {
    language: Language;
    setLanguage: (lang: Language) => void;

    contacts: Contact[];
    setContacts: (contacts: Contact[]) => void;
    silentMode: boolean;
    setSilentMode: (enabled: boolean) => void;
    t: (key: string) => string;
}

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export const useSettings = () => {
    const context = useContext(SettingsContext);
    if (!context) throw new Error('useSettings must be used within a SettingsProvider');
    return context;
};

const translations: Record<Language, Record<string, string>> = {
    en: {
        'nav.home': 'Home',
        'nav.help': 'Help',
        'nav.stories': 'Stories',
        'nav.more': 'More',
        'settings.title': 'Settings',
        'settings.tab.general': 'General',
        'settings.tab.safety': 'Safety',
        'settings.appearance': 'Appearance',
        'settings.dark_mode': 'Dark Mode',
        'settings.dark_mode.desc': 'Easier on the eyes',
        'settings.language': 'App Language',
        'settings.safety.title': 'Safety Configuration',
        'settings.safety.desc': 'Manage your emergency contacts and alert preferences here.',
        'settings.alert.title': 'Alert Preferences',
        'settings.alert.silent': 'Silent Alerts',
        'settings.alert.silent.desc': 'Send SOS without sound',

        'contacts.title': 'Trusted Contacts',
        'contacts.desc': 'These contacts will receive your SOS alerts with location.',
        'contacts.empty': 'No contacts added yet.',
        'contacts.add.name': 'Name (e.g. Mom)',
        'contacts.add.phone': 'Phone Number',
        'contacts.error.incomplete': 'Please fill in both fields',
        'contacts.error.phone': 'Please enter a valid phone number',
        'contacts.success.added': 'Contact added successfully',
        'contacts.success.removed': 'Contact removed',

        'nav.who_we_are': 'Who We Are',
        'nav.policy': 'Policy',
        'nav.impacts': 'Impacts',
        'nav.take_action': 'Take Action',
        'nav.services': 'Services',

        'hero.title_1': 'Your Voice,',
        'hero.title_2': 'Your Safety',
        'hero.subtitle': 'A safe space for women to speak, learn, and take action.',
        'hero.trusted_by': 'Trusted by 50,000+ Women',
        'hero.explore': 'Explore Our Work',
        'hero.get_help': 'Get Help Now',
        'hero.stat.support': 'Support',
        'hero.stat.helped': 'Women Helped',
        'hero.stat.cities': 'Cities',
        'hero.scroll': 'Scroll to explore',

        'tools.title': 'Essential Safety Tools',
        'tools.fakeCall': 'Fake Call',
        'tools.fake_call.desc': 'Simulate an incoming call to escape awkward situations.',
        'tools.safeRoute': 'Safe Route',
        'tools.safe_route.desc': 'Find nearest police stations and safe zones on Google Maps.',
        'tools.helplines': 'Emergency Directory',
        'tools.helpline.police': 'Police',
        'tools.helpline.women': 'Women Helpline',
        'tools.helpline.abuse': 'Domestic Abuse',
        'tools.helpline.ambulance': 'Ambulance',

        'fake_call.incoming': 'Incoming call...',
        'fake_call.decline': 'Decline',
        'fake_call.answer': 'Answer',
        'fake_call.caller': 'Mom',

        'mission.title': "We're here to",
        'mission.help': 'help.',
        'mission.our_mission': 'Our Mission',
        'mission.description_1': 'Our mission is to prevent gender-based violence and empower women through action. We work with communities, institutions, and individuals to build safer environments.',
        'mission.description_2': 'We strive to prevent violence, support and advocate for survivors, and empower women to reach their full potential through comprehensive safety programs.',
        'mission.learn_more': 'Learn more',
        'mission.download': 'Download',
        'mission.crisis_support.title': 'Crisis Support',
        'mission.crisis_support.desc': 'Immediate, confidential help when you need it most.',
        'mission.legal_advocacy.title': 'Legal Advocacy',
        'mission.legal_advocacy.desc': 'Guidance through systems that can feel overwhelming.',
        'mission.community_action.title': 'Community Action',
        'mission.community_action.desc': 'Training, workshops, and volunteer networks.',

        'testimonial.quote': '"I turned around and spoke up. That moment changed everything."',
        'testimonial.author': 'Vaishali',
        'testimonial.role': 'Student Advocate',
        'testimonial.share': 'Share Your Story',

        'stats.reality': 'The Reality',
        'stats.title': 'The challenge is',
        'stats.title_highlight': 'real.',
        'stats.stat_1.label': 'women experience sexual violence',
        'stats.stat_1.prefix': '1 in ',
        'stats.stat_2.label': 'of assaults go unreported',
        'stats.stat_2.suffix': '%',
        'stats.stat_3.label': 'a reported rape in India',
        'stats.stat_3.prefix': 'Every ',
        'stats.stat_3.suffix': ' min',
        'stats.stat_4.label': 'women in legislative seats',
        'stats.stat_4.prefix': '<',
        'stats.stat_4.suffix': '%',
        'stats.sources': 'Sources: NCRB, ILO, UN Women',
        'stats.view_report': 'View Full Report',

        'efforts.challenges_badge': 'Challenges We Face',
        'efforts.title': 'Efforts and',
        'efforts.title_highlight': 'challenges.',
        'efforts.subtitle': 'Laws exist. Technology exists. But gaps remain.',
        'efforts.challenge_1': 'Digital literacy in rural areas limits app usage.',
        'efforts.challenge_2': 'Police resources are stretched; response times vary.',
        'efforts.challenge_3': 'Cultural stigma still silences survivors.',
        'efforts.initiatives': 'See Our Initiatives',
        'efforts.years': '7 Years',
        'efforts.years_desc': 'Of continuous effort',

        'stories.title': 'Real stories. Real',
        'stories.title_highlight': 'impact.',
        'stories.read_more': 'Read more stories',
        'stories.story_1.label': 'Street Harassment',
        'stories.story_1.quote': '"No one said anything until I spoke up. Then they blamed me."',
        'stories.story_1.attr': 'Vaishali, Student',
        'stories.story_2.label': 'Institutional Failure',
        'stories.story_2.quote': '"A doctor should be safe in her own hospital."',
        'stories.story_2.attr': 'Kolkata case, August 2024',

        'community.title': 'Community & Support',
        'community.tab.forum': 'Community Forum',
        'community.tab.report': 'Anonymous Report',
        'community.forum.placeholder': 'Share your experience or ask for advice...',
        'community.forum.post': 'Post',
        'community.report.anonymous_badge': '100% Anonymous & Secure',
        'community.report.anonymous_desc': 'Your identity remains hidden. This report will be encrypted and sent to our safety audit team to identify high-risk zones.',
        'community.report.incident_type': 'Incident Type',
        'community.report.date_time': 'Date & Time (Approx)',
        'community.report.description': 'Description',
        'community.report.submit': 'Submit Report',

        'services.title': 'Our services and',
        'services.title_highlight': 'resources.',
        'services.view_all': 'View all services',
        'services.crisis.title': 'Crisis Intervention',
        'services.crisis.desc': '24/7 hotline for immediate support.',
        'services.legal.title': 'Legal Advocacy',
        'services.legal.desc': 'Support for navigating legal processes.',
        'services.counselling.title': 'Counselling',
        'services.counselling.desc': 'Trauma-informed care for healing.',
        'services.workshops.title': 'Workshops',
        'services.workshops.desc': 'Safety awareness and self-defense.',

        'defense.title': 'Self-defense',
        'defense.title_highlight': 'techniques.',
        'defense.practice_warning': 'Practice with a trained instructor.',
        'defense.tech_1.title': 'Wrist Escape',
        'defense.tech_1.desc': 'Break a wrist grip quickly.',
        'defense.tech_2.title': 'Choke Defense',
        'defense.tech_2.desc': 'Defend against a front choke.',
        'defense.tech_3.title': 'Bear Hug Escape',
        'defense.tech_3.desc': 'Escape a rear bear hug.',

        'support.title': 'Survivor support and',
        'support.title_highlight': 'advocacy.',
        'support.get_support': 'Get support',
        'support.card_1.title': 'Compassionate Listening',
        'support.card_1.desc': 'A safe, confidential space to share.',
        'support.card_2.title': 'Legal & Medical Help',
        'support.card_2.desc': 'Navigate systems with guidance.',
        'support.card_3.title': 'Support Groups',
        'support.card_3.desc': 'Connect with others who understand.',

        'education.title': 'Empowering women through',
        'education.title_highlight': 'education.',
        'education.item_1': 'Workshops on self-defense, safety awareness, and healthy relationships.',
        'education.item_2': 'Educational materials on rights and empowerment.',
        'education.item_3': 'Public awareness campaigns to challenge harmful norms.',
        'education.explore': 'Explore workshops',

        'jobs.title': 'Job & Skill',
        'jobs.resources': 'Resources',
        'jobs.courses': 'Free Skill Courses',
        'jobs.courses.desc': 'Access free courses on digital literacy, coding, and business management.',
        'jobs.courses.btn': 'Start Learning',
        'jobs.portals': 'Job Portals',
        'jobs.portals.desc': 'Find jobs tailored for women in various sectors including tech and healthcare.',
        'jobs.portals.btn': 'Find Jobs',
        'jobs.schemes': 'Government Schemes',
        'jobs.schemes.desc': 'Learn about government initiatives and financial aid for women entrepreneurs.',
        'jobs.schemes.btn': 'View Schemes',
        'jobs.subtitle': 'Empowering women with the skills and opportunities needed for economic independence.',

        'culture.title': 'Fostering a culture of',
        'culture.title_highlight': 'respect.',
        'culture.item_1': 'Advocate for legislation that promotes gender equality.',
        'culture.item_2': 'Work with schools, businesses, and communities to build respect.',
        'culture.item_3': 'Challenge stereotypes and biases at every level.',
        'culture.join': 'Join the movement',

        'guardian.title': '4. Crowd-Sourced Guardian Network (Verified)',
        'guardian.subtitle': 'Nearby verified citizens get alert • Like “Uber for safety help”',
        'guardian.verify_btn': 'Verified via Aadhaar / NGO ID',
        'guardian.card_1.title': 'NCC Cadets',
        'guardian.card_1.desc': 'Trained & Disciplined',
        'guardian.card_2.title': 'Security Guards',
        'guardian.card_2.desc': 'On-Site Authority',
        'guardian.card_3.title': 'NGOs',
        'guardian.card_3.desc': 'Community Support',
        'guardian.card_4.title': 'Female Volunteers',
        'guardian.card_4.desc': 'Empathy & Action',

        'footer.join': 'Join the',
        'footer.join_highlight': 'movement.',
        'auth.login.title': 'Welcome back',
        'auth.login.subtitle': 'Sign in to access your account',
        'auth.login.email': 'Email',
        'auth.login.password': 'Password',
        'auth.login.submit': 'Sign In',
        'auth.login.no_account': "Don't have an account?",
        'auth.login.signup_link': 'Sign up',

        'auth.signup.title': 'Create an account',
        'auth.signup.subtitle': 'Join the community to stay safe',
        'auth.signup.fullname': 'Full Name',
        'auth.signup.email': 'Email',
        'auth.signup.password': 'Password',
        'auth.signup.submit': 'Sign Up',
        'auth.signup.has_account': 'Already have an account?',
        'auth.signup.login_link': 'Sign in',

        'footer.description': 'Building a world where safety is a fundamental right, not a privilege.',
        'footer.volunteer': 'Become a Volunteer',
        'footer.partner': 'Partner with Us',
        'footer.connect': 'Connect Details (QR Code)',
        'footer.admin_login': 'Admin Login',
        'footer.rights': '© 2025 Suraksha. All rights reserved.',

        'footer.company': 'Company',
        'footer.about': 'About Us',
        'footer.careers': 'Careers',
        'footer.blog': 'Blog',
        'footer.press': 'Press',

        'footer.resources': 'Resources',
        'footer.safety_tips': 'Safety Tips',
        'footer.support': 'Support',
        'footer.community': 'Community',
        'footer.admin': 'Admin',

        'footer.join_title_1': 'Join the',
        'footer.join_title_2': 'Movement',
        'footer.join_desc': 'Be part of the change. Join us in building a safer world for everyone.',
        'footer.partner_button': 'Partner with Us',

        'rights.title': 'Know Your Rights',
        'rights.dv.title': 'Protection of Women from Domestic Violence Act, 2005',
        'rights.dv.desc': 'Protects women from physical, emotional, sexual, and economic abuse at home. You have the right to a shared household and separate residence.',
        'rights.posh.title': 'Sexual Harassment of Women at Workplace (POSH) Act, 2013',
        'rights.posh.desc': 'Mandates an Internal Complaints Committee (ICC) in every organization with 10+ employees. Protects against unwelcome physical, verbal, or non-verbal conduct.',
        'rights.cyber.title': 'Cyber Crime & IT Act',
        'rights.cyber.desc': 'Addresses online stalking, bullying, and image abuse. You can file a complaint at cybercrime.gov.in anonymously.',
        'rights.fir.title': 'Zero FIR Rights',
        'rights.fir.desc': 'A police station cannot refuse to register an FIR based on jurisdiction. You can file it anywhere, and it will be transferred to the concerned station.',

        'video.title': 'Report Safety Issue (Video)',
        'video.subtitle': 'Upload or record a video of any safety concern. It will be sent directly to our safety team for immediate action.',
        'video.upload_btn': 'Upload Video',
        'video.record_btn': 'Record Video',
        'video.submit_btn': 'Submit Report',
        'video.desc_placeholder': 'Describe the incident (optional)...',
        'video.success': 'Video report submitted successfully. Our team is reviewing it.',
        'video.file_selected': 'File selected:',
        'video.recording': 'Recording...',
        'video.stop_recording': 'Stop Recording',

        'portfolio.nav': 'My Work',
        'portfolio.title': 'Featured Projects & Skills',
        'portfolio.projects.title': 'Featured Projects',
        'portfolio.skills.title': 'Technical Skills',
        'portfolio.taskflow.desc': 'A full-stack task management platform with JWT auth and real-time dashboard.',
        'portfolio.agriculture.desc': 'IoT-based soil monitoring and crop recommendation system using AI analytics.',
        'portfolio.skills.mern': 'MERN Stack (MongoDB, Express, React, Node.js)',
        'portfolio.skills.frontend': 'Frontend: Next.js, TypeScript, TailwindCSS, GSAP',
        'portfolio.skills.backend': 'Backend: REST APIs, JWT, Mongoose, Railway',
        'portfolio.skills.iot': 'IoT & AI: Python, Arduino, Data Visualization',
    },
    hi: {
        'nav.home': 'मुख्य पृष्ठ',
        'nav.help': 'मदद',
        'nav.stories': 'कहानियां',
        'nav.more': 'अधिक',
        'settings.title': 'सेटिंग्स',
        'settings.tab.general': 'सामान्य',
        'settings.tab.safety': 'सुरक्षा',
        'settings.appearance': 'दिखावट',
        'settings.dark_mode': 'डार्क मोड',
        'settings.dark_mode.desc': 'आंखों के लिए आरामदायक',
        'settings.language': 'ऐप की भाषा',
        'settings.safety.title': 'सुरक्षा विन्यास',
        'settings.safety.desc': 'अपने आपातकालीन संपर्क और अलर्ट प्राथमिकताएं यहां प्रबंधित करें।',
        'settings.alert.title': 'अलर्ट प्राथमिकताएं',
        'settings.alert.silent': 'साइलेंट अलर्ट',
        'settings.alert.silent.desc': 'बिना आवाज के SOS भेजें',

        'contacts.title': 'विश्वसनीय संपर्क',
        'contacts.desc': 'इन संपर्कों को स्थान के साथ आपके SOS अलर्ट प्राप्त होंगे।',
        'contacts.empty': 'अभी तक कोई संपर्क नहीं जोड़ा गया।',
        'contacts.add.name': 'नाम (उदा. माँ)',
        'contacts.add.phone': 'फ़ोन नंबर',
        'contacts.error.incomplete': 'कृपया दोनों फ़ील्ड भरें',
        'contacts.error.phone': 'कृपया एक मान्य फ़ोन नंबर दर्ज करें',
        'contacts.success.added': 'संपर्क सफलतापूर्वक जोड़ा गया',
        'contacts.success.removed': 'संपर्क हटा दिया गया',

        'nav.who_we_are': 'हम कौन हैं',
        'nav.policy': 'नीति',
        'nav.impacts': 'प्रभाव',
        'nav.take_action': 'कार्रवाई करें',
        'nav.services': 'सेवाएं',

        'hero.title_1': 'आपकी आवाज़,',
        'hero.title_2': 'आपकी सुरक्षा',
        'hero.subtitle': 'महिलाओं के लिए बोलने, सीखने और कार्रवाई करने का एक सुरक्षित स्थान।',
        'hero.trusted_by': '50,000+ महिलाओं द्वारा विश्वसनीय',
        'hero.explore': 'हमारा काम देखें',
        'hero.get_help': 'अभी मदद लें',
        'hero.stat.support': 'समर्थन',
        'hero.stat.helped': 'महिलाएं लाभांवित',
        'hero.stat.cities': 'शहर',
        'hero.scroll': 'अन्वेषण के लिए स्क्रॉल करें',

        'tools.title': 'आवश्यक सुरक्षा उपकरण',
        'tools.fakeCall': 'फर्जी कॉल',
        'tools.fake_call.desc': 'असहज स्थितियों से बचने के लिए एक इनकमिंग कॉल अनुकरण करें।',
        'tools.safeRoute': 'सुरक्षित मार्ग',
        'tools.safe_route.desc': 'Google मैप्स पर निकटतम पुलिस स्टेशन और सुरक्षित क्षेत्र खोजें।',
        'tools.helplines': 'आपातकालीन निर्देशिका',
        'tools.helpline.police': 'पुलिस',
        'tools.helpline.women': 'महिला हेल्पलाइन',
        'tools.helpline.abuse': 'घरेलू हिंसा',
        'tools.helpline.ambulance': 'एम्बुलेंस',

        'fake_call.incoming': 'आने वाली कॉल...',
        'fake_call.decline': 'अस्वीकार करें',
        'fake_call.answer': 'उत्तर दें',
        'fake_call.caller': 'माँ',

        'mission.title': 'हम यहाँ हैं',
        'mission.help': 'मदद के लिए।',
        'mission.our_mission': 'हमारा मिशन',
        'mission.description_1': 'हमारा मिशन लिंग आधारित हिंसा को रोकना और कार्रवाई के माध्यम से महिलाओं को सशक्त बनाना है। हम सुरक्षित वातावरण बनाने के लिए समुदायों, संस्थानों और व्यक्तियों के साथ काम करते हैं।',
        'mission.description_2': 'हम हिंसा को रोकने, बचे लोगों का समर्थन करने और वकालत करने और व्यापक सुरक्षा कार्यक्रमों के माध्यम से महिलाओं को उनकी पूरी क्षमता तक पहुंचने के लिए सशक्त बनाने का प्रयास करते हैं।',
        'mission.learn_more': 'और अधिक जानें',
        'mission.download': 'डाउनलोड',
        'mission.crisis_support.title': 'संकट सहायता',
        'mission.crisis_support.desc': 'जब आपको सबसे अधिक आवश्यकता हो, तब तत्काल, गोपनीय मदद।',
        'mission.legal_advocacy.title': 'कानूनी वकालत',
        'mission.legal_advocacy.desc': 'उन प्रणालियों के माध्यम से मार्गदर्शन जो भारी लग सकती हैं।',
        'mission.community_action.title': 'सामुदायिक कार्रवाई',
        'mission.community_action.desc': 'प्रशिक्षण, कार्यशालाएं और स्वयंसेवक नेटवर्क।',

        'testimonial.quote': '"मैं मुड़ी और मैंने बात की। उस पल ने सब कुछ बदल दिया।"',
        'testimonial.author': 'वैशाली',
        'testimonial.role': 'छात्र अधिवक्ता',
        'testimonial.share': 'अपनी कहानी साझा करें',

        'stats.reality': 'हकीकत',
        'stats.title': 'चुनौती',
        'stats.title_highlight': 'असली है।',
        'stats.stat_1.label': 'महिलाएं यौन हिंसा का अनुभव करती हैं',
        'stats.stat_1.prefix': 'में 1 ',
        'stats.stat_2.label': 'हमले रिपोर्ट नहीं किए जाते',
        'stats.stat_2.suffix': '%',
        'stats.stat_3.label': 'भारत में एक रिपोर्ट की गई बलात्कार',
        'stats.stat_3.prefix': 'हर ',
        'stats.stat_3.suffix': ' मिनट',
        'stats.stat_4.label': 'विधायी सीटों में महिलाएं',
        'stats.stat_4.prefix': '<',
        'stats.stat_4.suffix': '%',
        'stats.sources': 'स्रोत: NCRB, ILO, UN Women',
        'stats.view_report': 'पूरी रिपोर्ट देखें',

        'efforts.challenges_badge': 'हमारे सामने चुनौतियां',
        'efforts.title': 'प्रयास और',
        'efforts.title_highlight': 'चुनौतियां।',
        'efforts.subtitle': 'कानून मौजूद हैं। तकनीक मौजूद है। लेकिन कमियां बनी हुई हैं।',
        'efforts.challenge_1': 'ग्रामीण क्षेत्रों में डिजिटल साक्षरता ऐप के उपयोग को सीमित करती है।',
        'efforts.challenge_2': 'पुलिस संसाधन कम हैं; प्रतिक्रिया समय अलग-अलग होता है।',
        'efforts.challenge_3': 'सांस्कृतिक कलंक अभी भी बचे लोगों को चुप कराता है।',
        'efforts.initiatives': 'हमारी पहल देखें',
        'efforts.years': '7 साल',
        'efforts.years_desc': 'निरंतर प्रयास के',

        'stories.title': 'सच्ची कहानियां। असली',
        'stories.title_highlight': 'प्रभाव।',
        'stories.read_more': 'और कहानियां पढ़ें',
        'stories.story_1.label': 'सड़क पर उत्पीड़न',
        'stories.story_1.quote': '"किसी ने कुछ नहीं कहा जब तक मैंने नहीं बोला। फिर उन्होंने मुझे दोषी ठहराया।"',
        'stories.story_1.attr': 'वैशाली, छात्र',
        'stories.story_2.label': 'संस्थागत विफलता',
        'stories.story_2.quote': '"एक डॉक्टर को अपने ही अस्पताल में सुरक्षित होना चाहिए।"',
        'stories.story_2.attr': 'कोलकाता मामला, अगस्त 2024',

        'community.title': 'समुदाय और समर्थन',
        'community.tab.forum': 'सामुदायिक मंच',
        'community.tab.report': 'गुमनाम रिपोर्ट',
        'community.forum.placeholder': 'अपना अनुभव साझा करें या सलाह मांगें...',
        'community.forum.post': 'पोस्ट करें',
        'community.report.anonymous_badge': '100% गुमनाम और सुरक्षित',
        'community.report.anonymous_desc': 'आपकी पहचान छिपी रहती है। यह रिपोर्ट एन्क्रिप्ट की जाएगी और उच्च जोखिम वाले क्षेत्रों की पहचान करने के लिए हमारी सुरक्षा ऑडिट टीम को भेजी जाएगी।',
        'community.report.incident_type': 'घटना का प्रकार',
        'community.report.date_time': 'तारीख और समय (अनुमानित)',
        'community.report.description': 'विवरण',
        'community.report.submit': 'रिपोर्ट जमा करें',

        'services.title': 'हमारी सेवाएं और',
        'services.title_highlight': 'संसाधन।',
        'services.view_all': 'सभी सेवाएं देखें',
        'services.crisis.title': 'संकट हस्तक्षेप',
        'services.crisis.desc': 'तत्काल सहायता के लिए 24/7 हॉटलाइन।',
        'services.legal.title': 'कानूनी वकालत',
        'services.legal.desc': 'कानूनी प्रक्रियाओं को नेविगेट करने के लिए समर्थन।',
        'services.counselling.title': 'परामर्श',
        'services.counselling.desc': 'उपचार के लिए आघात-सूचित देखभाल।',
        'services.workshops.title': 'कार्यशालाएं',
        'services.workshops.desc': 'सुरक्षा जागरूकता और आत्मरक्षा।',

        'defense.title': 'आत्मरक्षा',
        'defense.title_highlight': 'तकनीकें।',
        'defense.practice_warning': 'एक प्रशिक्षित प्रशिक्षक के साथ अभ्यास करें।',
        'defense.tech_1.title': 'कलाई छुड़ाना',
        'defense.tech_1.desc': 'कलाई की पकड़ को जल्दी से तोड़ें।',
        'defense.tech_2.title': 'गला घोंटने से बचाव',
        'defense.tech_2.desc': 'सामने से गला घोंटने से बचाव करें।',
        'defense.tech_3.title': 'बेयर हग से बचाव',
        'defense.tech_3.desc': 'पीछे से जकड़ लेने से बचें।',

        'support.title': 'बचे लोगों का समर्थन और',
        'support.title_highlight': 'वकालत।',
        'support.get_support': 'समर्थन प्राप्त करें',
        'support.card_1.title': 'सहानुभूतिपूर्ण सुनना',
        'support.card_1.desc': 'साझा करने के लिए एक सुरक्षित, गोपनीय स्थान।',
        'support.card_2.title': 'कानूनी और चिकित्सा सहायता',
        'support.card_2.desc': 'मार्गदर्शन के साथ सिस्टम नेविगेट करें।',
        'support.card_3.title': 'समर्थन समूह',
        'support.card_3.desc': 'उन लोगों के साथ जुड़ें जो समझते हैं।',

        'education.title': 'शिक्षा के माध्यम से महिलाओं को',
        'education.title_highlight': 'सशक्त बनाना।',
        'education.item_1': 'आत्मरक्षा, सुरक्षा जागरूकता और स्वस्थ संबंधों पर कार्यशालाएं।',
        'education.item_2': 'अधिकारों और सशक्तिकरण पर शैक्षिक सामग्री।',
        'education.item_3': 'हानिकारक मानदंडों को चुनौती देने के लिए जन जागरूकता अभियान।',
        'education.explore': 'कार्यशालाएं देखें',

        'jobs.title': 'नौकरी और कौशल',
        'jobs.resources': 'संसाधन',
        'jobs.courses': 'मुफ्त कौशल पाठ्यक्रम',
        'jobs.courses.desc': 'डिजिटल साक्षरता, कोडिंग और व्यवसाय प्रबंधन पर मुफ्त पाठ्यक्रमों तक पहुंचें।',
        'jobs.courses.btn': 'सीखना शुरू करें',
        'jobs.portals': 'नौकरी पोर्टल',
        'jobs.portals.desc': 'तकनीक और स्वास्थ्य सेवा सहित विभिन्न क्षेत्रों में महिलाओं के लिए उपयुक्त नौकरियां खोजें।',
        'jobs.portals.btn': 'नौकरियां खोजें',
        'jobs.schemes': 'सरकारी योजनाएं',
        'jobs.schemes.desc': 'महिला उद्यमियों के लिए सरकारी पहल और वित्तीय सहायता के बारे में जानें।',
        'jobs.schemes.btn': 'योजनाएं देखें',
        'jobs.subtitle': 'आर्थिक स्वतंत्रता के लिए आवश्यक कौशल और अवसरों के साथ महिलाओं को सशक्त बनाना।',

        'culture.title': 'सम्मान की संस्कृति को',
        'culture.title_highlight': 'बढ़ावा देना।',
        'culture.item_1': 'लैंगिक समानता को बढ़ावा देने वाले कानून की वकालत करें।',
        'culture.item_2': 'सम्मान बनाने के लिए स्कूलों, व्यवसायों और समुदायों के साथ काम करें।',
        'culture.item_3': 'हर स्तर पर रूढ़ियों और पूर्वाग्रहों को चुनौती दें।',
        'culture.join': 'आंदोलन में शामिल हों',

        'guardian.title': '4. क्राउड-सोर्स्ड गार्डियन नेटवर्क (सत्यापित)',
        'guardian.subtitle': 'पास के सत्यापित नागरिकों को अलर्ट मिलता है • सुरक्षा मदद के लिए "Uber" की तरह',
        'guardian.verify_btn': 'आधार / एनजीओ आईडी के माध्यम से सत्यापित',
        'guardian.card_1.title': 'एनसीसी कैडेट्स',
        'guardian.card_1.desc': 'प्रशिक्षित और अनुशासित',
        'guardian.card_2.title': 'सुरक्षा गार्ड',
        'guardian.card_2.desc': 'ऑन-साइट अथॉरिटी',
        'guardian.card_3.title': 'एनजीओ',
        'guardian.card_3.desc': 'सामुदायिक समर्थन',
        'guardian.card_4.title': 'महिला स्वयंसेवक',
        'guardian.card_4.desc': 'सहानुभूति और कार्रवाई',

        'footer.join': 'शामिल हों',
        'footer.join_highlight': 'आंदोलन में।',
        'auth.login.title': 'वापसी पर स्वागत है',
        'auth.login.subtitle': 'अपने खाते तक पहुंचने के लिए साइन इन करें',
        'auth.login.email': 'ईमेल',
        'auth.login.password': 'पासवर्ड',
        'auth.login.submit': 'साइन इन करें',
        'auth.login.no_account': 'खाता नहीं है?',
        'auth.login.signup_link': 'साइन अप करें',

        'auth.signup.title': 'खाता बनाएं',
        'auth.signup.subtitle': 'सुरक्षित रहने के लिए समुदाय में शामिल हों',
        'auth.signup.fullname': 'पूरा नाम',
        'auth.signup.email': 'ईमेल',
        'auth.signup.password': 'पासवर्ड',
        'auth.signup.submit': 'साइन अप करें',
        'auth.signup.has_account': 'क्या आपके पास पहले से एक खाता मौजूद है?',
        'auth.signup.login_link': 'साइन इन करें',

        'footer.description': 'एक ऐसी दुनिया का निर्माण करना जहाँ सुरक्षा एक मौलिक अधिकार है, विशेषाधिकार नहीं।',
        'footer.volunteer': 'स्वयंसेवक बनें',
        'footer.partner': 'हमारे साथ जुड़ें',
        'footer.connect': 'कनेक्ट विवरण (क्यूआर कोड)',
        'footer.admin_login': 'एडमिन लॉगिन',
        'footer.rights': '© 2025 सुरक्षा। सर्वाधिकार सुरक्षित।',

        'footer.company': 'कंपनी',
        'footer.about': 'हमारे बारे में',
        'footer.careers': 'करियर',
        'footer.blog': 'ब्लॉग',
        'footer.press': 'प्रेस',

        'footer.resources': 'संसाधन',
        'footer.safety_tips': 'सुरक्षा सुझाव',
        'footer.support': 'समर्थन',
        'footer.community': 'समुदाय',
        'footer.admin': 'प्रशासक',

        'footer.join_title_1': 'शामिल हों',
        'footer.join_title_2': 'आंदोलन',
        'footer.join_desc': 'बदलाव का हिस्सा बनें। सभी के लिए एक सुरक्षित दुनिया बनाने में हमारे साथ जुड़ें।',
        'footer.partner_button': 'हमारे साथ जुड़ें',

        'rights.title': 'अपने अधिकारों को जानें',
        'rights.dv.title': 'घरेलू हिंसा से महिलाओं का संरक्षण अधिनियम, 2005',
        'rights.dv.desc': 'महिलाओं को घर पर शारीरिक, भावनात्मक, यौन और आर्थिक शोषण से बचाता है। आपको साझा घर और अलग निवास का अधिकार है।',
        'rights.posh.title': 'कार्यस्थल पर महिलाओं का यौन उत्पीड़न (POSH) अधिनियम, 2013',
        'rights.posh.desc': '10+ कर्मचारियों वाले प्रत्येक संगठन में एक आंतरिक शिकायत समिति (ICC) अनिवार्य करता है। अवांछित शारीरिक, मौखिक या गैर-मौखिक आचरण से बचाता है।',
        'rights.cyber.title': 'साइबर अपराध और आईटी अधिनियम',
        'rights.cyber.desc': 'ऑनलाइन पीछा करने, धमकाने और छवियों के दुरुपयोग को संबोधित करता है। आप cybercrime.gov.in पर गुमनाम रूप से शिकायत दर्ज कर सकते हैं।',
        'rights.fir.title': 'जीरो एफआईआर अधिकार',
        'rights.fir.desc': 'एक पुलिस स्टेशन अधिकार क्षेत्र के आधार पर एफआईआर दर्ज करने से मना नहीं कर सकता। आप इसे कहीं भी फाइल कर सकते हैं, और इसे संबंधित स्टेशन पर स्थानांतरित कर दिया जाएगा।',

        'video.title': 'सुरक्षा समस्या की रिपोर्ट करें (वीडियो)',
        'video.subtitle': 'किसी भी सुरक्षा चिंता का वीडियो अपलोड या रिकॉर्ड करें। इसे तत्काल कार्रवाई के लिए सीधे हमारी सुरक्षा टीम को भेजा जाएगा।',
        'video.upload_btn': 'वीडियो अपलोड करें',
        'video.record_btn': 'वीडियो रिकॉर्ड करें',
        'video.submit_btn': 'रिपोर्ट जमा करें',
        'video.desc_placeholder': 'घटना का वर्णन करें (वैकल्पिक)...',
        'video.success': 'वीडियो रिपोर्ट सफलतापूर्वक जमा हो गई। हमारी टीम इसकी समीक्षा कर रही है।',
        'video.file_selected': 'फ़ाइल चुनी गई:',
        'video.recording': 'रिकॉर्डिंग...',
        'video.stop_recording': 'रिकॉर्डिंग बंद करें',

        'portfolio.nav': 'मेरा काम',
        'portfolio.title': 'प्रमुख प्रोजेक्ट्स और कौशल',
        'portfolio.projects.title': 'प्रमुख प्रोजेक्ट्स',
        'portfolio.skills.title': 'तकनीकी कौशल',
        'portfolio.taskflow.desc': 'JWT प्रमाणीकरण और रीयल-टाइम डैशबोर्ड वाला एक फुल-स्टैक टास्क मैनेजमेंट प्लेटफॉर्म।',
        'portfolio.agriculture.desc': 'AI एनालिटिक्स का उपयोग करके IoT-आधारित मिट्टी की निगरानी और फसल अनुशंसा प्रणाली।',
        'portfolio.skills.mern': 'MERN स्टैक (MongoDB, Express, React, Node.js)',
        'portfolio.skills.frontend': 'फ्रंटएंड: Next.js, TypeScript, TailwindCSS, GSAP',
        'portfolio.skills.backend': 'बैकएंड: REST APIs, JWT, Mongoose, Railway',
        'portfolio.skills.iot': 'IoT और AI: Python, Arduino, डेटा विज़ुअलाइज़ेशन',
    }
};

interface SettingsProviderProps {
    children: React.ReactNode;
}

export const SettingsProvider: React.FC<SettingsProviderProps> = ({ children }) => {
    const [language, setLanguage] = useLocalStorage<Language>('app-language', 'en');
    const [contacts, setContacts] = useLocalStorage<Contact[]>('suraksha-contacts', [
        { id: '1', name: 'Emergency Services', phone: '112' }
    ]);
    const [silentMode, setSilentMode] = useLocalStorage<boolean>('app-silent-mode', false);

    const t = (key: string): string => {
        const langData = translations[language];
        return (langData as any)[key] || key;
    };

    return (
        <SettingsContext.Provider value={{
            language,
            setLanguage,
            contacts,
            setContacts,
            silentMode,
            setSilentMode,
            t
        }}>
            {children}
        </SettingsContext.Provider>
    );
};
